libmultirom: Add missing libbootimg dependency
 * Fix the following references :

  lib/inject.c:276: error: undefined reference to 'libbootimg_init_load'
  lib/inject.c:329: error: undefined reference to 'libbootimg_destroy'
  lib/inject.c:292: error: undefined reference to 'libbootimg_dump_ramdisk'
  lib/inject.c:306: error: undefined reference to 'libbootimg_load_ramdisk'
  lib/inject.c:315: error: undefined reference to 'libbootimg_write_img'

Change-Id: Ie8714598d24fd2ca0abb85471b113d23125bab1a